ALTER TABLE student MODIFY birthday DATE NOT NULL;
ALTER TABLE mark MODIFY mark INT CHECK (mark >= 1 AND mark <= 10);
ALTER TABLE mark MODIFY student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY subject_id BIGINT NOT NULL;
ALTER TABLE subject MODIFY grade INT CHECK (grade >= 1 AND grade <= 5);
ALTER TABLE paymenttype ADD UNIQUE (name);
ALTER TABLE payment MODIFY type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY amount DECIMAL NOT NULL;
ALTER TABLE payment MODIFY payment_date DATETIME NOT NULL;